/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor.janela;

/**
 *
 * @author lab-04-18
 */
import conversor.Constante;
import java.awt.Color;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import conversor.Conversor;
import java.awt.Font;

public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    private String numero;
    char caractrs[];
    char origem, destino;

    public JanelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldConversao = new javax.swing.JTextField();
        jRadioButtonBinario = new javax.swing.JRadioButton();
        jRadioButtonDecimal = new javax.swing.JRadioButton();
        jRadioButtonHexadecimal = new javax.swing.JRadioButton();
        jRadioButtonRomano = new javax.swing.JRadioButton();
        jRadioButtonArabe = new javax.swing.JRadioButton();
        jRadioButtonDbinario = new javax.swing.JRadioButton();
        jRadioButtonDdecimal = new javax.swing.JRadioButton();
        jRadioButtonDhexadecimal = new javax.swing.JRadioButton();
        jRadioButtonDromano = new javax.swing.JRadioButton();
        jRadioButtonDarabe = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelMessagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(415, 370));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        jTextFieldConversao.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jTextFieldConversao.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldConversao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldConversao.setText("Introduz o número a ser convertido");
        jTextFieldConversao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextFieldConversao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConversaoActionPerformed(evt);
            }
        });
        jTextFieldConversao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldConversaoKeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBinario);
        jRadioButtonBinario.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonBinario.setText("Binário");
        jRadioButtonBinario.setOpaque(false);
        jRadioButtonBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBinarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDecimal);
        jRadioButtonDecimal.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDecimal.setText("Decimal");
        jRadioButtonDecimal.setOpaque(false);
        jRadioButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDecimalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonHexadecimal);
        jRadioButtonHexadecimal.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonHexadecimal.setText("Hexadecimal");
        jRadioButtonHexadecimal.setOpaque(false);
        jRadioButtonHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHexadecimalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRomano);
        jRadioButtonRomano.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonRomano.setText("Romano");
        jRadioButtonRomano.setOpaque(false);
        jRadioButtonRomano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRomanoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonArabe);
        jRadioButtonArabe.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonArabe.setText("Arabe");
        jRadioButtonArabe.setOpaque(false);
        jRadioButtonArabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonArabeActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonDbinario);
        jRadioButtonDbinario.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDbinario.setText("Binário");
        jRadioButtonDbinario.setOpaque(false);
        jRadioButtonDbinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDbinarioActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonDdecimal);
        jRadioButtonDdecimal.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDdecimal.setText("Decimal");
        jRadioButtonDdecimal.setOpaque(false);
        jRadioButtonDdecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDdecimalActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonDhexadecimal);
        jRadioButtonDhexadecimal.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDhexadecimal.setText("Hexadecimal");
        jRadioButtonDhexadecimal.setOpaque(false);
        jRadioButtonDhexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDhexadecimalActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonDromano);
        jRadioButtonDromano.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDromano.setText("Romano");
        jRadioButtonDromano.setOpaque(false);
        jRadioButtonDromano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDromanoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonDarabe);
        jRadioButtonDarabe.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDarabe.setText("Arabe");
        jRadioButtonDarabe.setOpaque(false);
        jRadioButtonDarabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDarabeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema de origem");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de destino");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Converter");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelMessagem.setForeground(java.awt.Color.red);
        jLabelMessagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMessagem.setText("  ");
        jLabelMessagem.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonArabe)
                                    .addComponent(jRadioButtonRomano)
                                    .addComponent(jRadioButtonHexadecimal)
                                    .addComponent(jRadioButtonDecimal)
                                    .addComponent(jRadioButtonBinario)
                                    .addComponent(jLabel2))
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jRadioButtonDarabe)
                                        .addComponent(jRadioButtonDromano)
                                        .addComponent(jRadioButtonDhexadecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonDdecimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonDbinario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)))
                            .addComponent(jLabelMessagem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTextFieldConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonBinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDecimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonHexadecimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonRomano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonArabe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonDbinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDdecimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDhexadecimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonDromano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDarabe)))
                .addGap(3, 3, 3)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMessagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 402, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversor/img/fundo.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, -5, 400, 350);

        jMenu1.setText("Ficheiro");

        jMenuItem1.setText("Importar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exportar");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldConversaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConversaoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (numero.length() > 0 && evt.getKeyCode() == evt.VK_BACK_SPACE) {
            numero = numero.substring(0, numero.length() - 1);
            System.err.println("Raul");
        }
        boolean b = conversor.Conversor.verificaExistCaracter(c, caractrs);
        if (b) {
            numero += c;
            System.err.println(numero);
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldConversaoKeyTyped

    private void jRadioButtonBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBinarioActionPerformed
        // TODO add your handling code here:
        setSistemaOrigem(Constante.BINARIO);
    }//GEN-LAST:event_jRadioButtonBinarioActionPerformed
    public void setSistemaOrigem(char c) {
        origem = c;
        caractrs = Conversor.sistema(c);
        numero = "";
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean b1, b2;
        b1 = b2 = true;
        try {
            boolean s = buttonGroup1.getSelection().isSelected();
            System.out.println(s);
        } catch (Exception e) {
            b1 = false;
        }

        try {
            boolean s = buttonGroup2.getSelection().isSelected();
            System.out.println(s);
        } catch (Exception e) {
            b2 = false;
        }
        if (b1 == false && b2 == false) {
            jLabelMessagem.setText("Selecione o sistema de origem e o sistema de destino");
            return;
        }
        if (b1 == true && b2 == true) {
            jLabelMessagem.setText("Conversão feita com sucesso");
            jLabelMessagem.setForeground(Color.BLACK);
            jLabelMessagem.setBackground(Color.white);
            String resultado = Conversor.converter(numero, origem, destino);
            jLabelMessagem.setText(resultado);
            jLabelMessagem.setFont(new Font(jLabelMessagem.getFont().getFontName(),jLabelMessagem.getFont().getStyle(), 24));

            return;
        }
        if (!b1) {
            jLabelMessagem.setText("Selecione o sistema de origem ");
            return;
        }
        if (!b2) {
            jLabelMessagem.setText("Selecione o sistema de destino");
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDecimalActionPerformed
        // TODO add your handling code here:
        setSistemaOrigem(Constante.DECIMAL);
    }//GEN-LAST:event_jRadioButtonDecimalActionPerformed

    private void jRadioButtonHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHexadecimalActionPerformed
        // TODO add your handling code here:
        caractrs = Conversor.sistema(Constante.HEXADECIMAL);
    }//GEN-LAST:event_jRadioButtonHexadecimalActionPerformed

    private void jRadioButtonRomanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRomanoActionPerformed
        // TODO add your handling code here:
        setSistemaOrigem(Constante.ROMANANO);
    }//GEN-LAST:event_jRadioButtonRomanoActionPerformed

    private void jRadioButtonArabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonArabeActionPerformed
        // TODO add your handling code here:
        setSistemaOrigem(Constante.DECIMAL);
    }//GEN-LAST:event_jRadioButtonArabeActionPerformed

    private void jRadioButtonDbinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDbinarioActionPerformed
        // TODO add your handling code here:
        destino = Constante.BINARIO;
    }//GEN-LAST:event_jRadioButtonDbinarioActionPerformed

    private void jRadioButtonDdecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDdecimalActionPerformed
        // TODO add your handling code here:
        destino = Constante.DECIMAL;
    }//GEN-LAST:event_jRadioButtonDdecimalActionPerformed

    private void jRadioButtonDhexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDhexadecimalActionPerformed
        // TODO add your handling code here:
        destino = Constante.HEXADECIMAL;
    }//GEN-LAST:event_jRadioButtonDhexadecimalActionPerformed

    private void jRadioButtonDromanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDromanoActionPerformed
        // TODO add your handling code here:
        destino = Constante.ROMANANO;
    }//GEN-LAST:event_jRadioButtonDromanoActionPerformed

    private void jRadioButtonDarabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDarabeActionPerformed
        // TODO add your handling code here:
        destino = Constante.DECIMAL;
    }//GEN-LAST:event_jRadioButtonDarabeActionPerformed

    private void jTextFieldConversaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConversaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConversaoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMessagem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonArabe;
    private javax.swing.JRadioButton jRadioButtonBinario;
    private javax.swing.JRadioButton jRadioButtonDarabe;
    private javax.swing.JRadioButton jRadioButtonDbinario;
    private javax.swing.JRadioButton jRadioButtonDdecimal;
    private javax.swing.JRadioButton jRadioButtonDecimal;
    private javax.swing.JRadioButton jRadioButtonDhexadecimal;
    private javax.swing.JRadioButton jRadioButtonDromano;
    private javax.swing.JRadioButton jRadioButtonHexadecimal;
    private javax.swing.JRadioButton jRadioButtonRomano;
    private javax.swing.JTextField jTextFieldConversao;
    // End of variables declaration//GEN-END:variables
}
